### ISSUE TITLE
UnicodeEncodeError in Podcasts fetcher

### ISSUE THREAD

**Issue by AnsgarSchmidt** [AnsgarSchmidt/aldebaran#5]
(server)ansi@ansinas:~/aldebaran/server$ python main.py
0.17.0
20 episodes at Forschung Aktuell - Deutschlandfunk
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    podcasts = Podcasts()
  File "/tank/ansi/aldebaran/server/Podcasts.py", line 96, in **init**
    p = Podcast(podcastLink)
  File "/tank/ansi/aldebaran/server/Podcasts.py", line 62, in **init**
    self.refresh()
  File "/tank/ansi/aldebaran/server/Podcasts.py", line 89, in refresh
    print "%d episodes at %s"%(len(self._links), self._name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 16: ordinal not in range(128)

**Comment by AnsgarSchmidt** [comment]
Working on it.

**Comment by AnsgarSchmidt** [comment]
Error is not in python, its on your bash. 
Try 

``` bash
export LC_ALL=en_US.UTF-8
```
